name: 'Deploy-to-multiple-aws-accounts'

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
permissions: read-all
jobs:
  DeployToAccountA:
    #if: github.event.pull_request.merged == true
    name: 'deploy-to-account-A'
    permissions:
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/deploy.yml
    with:
      working-directory: ./accounts/AccountA
      environment: AccountA
    secrets: inherit

  # DeployToAccountB:
  #   name: 'deploy-to-account-B'
  #   needs: DeployToAccountA
  #   permissions:
  #     pull-requests: write
  #     id-token: write
  #     contents: read

  #   uses: ./.github/workflows/deploy.yml
  #   with:
  #     working-directory: ./accounts/AccountB
  #     environment: AccountB
  #   secrets: inherit
